package agents;

public enum EchoType {
	CLEARED_TO_LAND, CLEARANCE_GRANTED, CONTACT_GROUND_CONTROL, USE_THIS_ROUTE, CD_CLEARANCE_GRANTED, HERE_IS_MODE, PUSHBACK_GRANTED, HERE_ARE_INSTRUCTIONS, POSITION_AND_HOLD, CLEARED_FOR_TAKEOFF, GOOD_BYE
}	
